name: Linters

on:
  pull_request:
  push:
jobs:
  linters:
    name: Linters

    runs-on: ubuntu-latest

    strategy:
      matrix:
        nix:
          - version: 2.10.3
            url: https://releases.nixos.org/nix/nix-2.10.3/install

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v17
        with:
          install_url: ${{ matrix.nix.url }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable binary cache (optional)
        uses: cachix/cachix-action@v10
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check EditorConfig
        run: nix-shell --run "editorconfig-checker"

      - name: Check flake8
        run: nix-shell --run "flake8 manual/preprocess.py"

      - name: Check rustfmt
        run: nix-shell --run "cargo fmt --check"
