name: Deploy Stable Manual

on:
  push:
    branches:
      - release-0.3.x
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://releases.nixos.org/nix/nix-2.4/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check API version
        run: echo "api_version=$(nix eval .#colmena.apiVersion | sed 's|\"||g')" >> $GITHUB_ENV

      - name: Check latest stable API version
        run: echo "latest_stable_api=$(curl -L https://raw.githubusercontent.com/zhaofengli/colmena/main/.github/latest_stable_api)" >> $GITHUB_ENV

      # == Manual
      - name: Build manual
        run: nix build .#manual -L

      - name: Deploy manual
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: result
          target-folder: '${{ env.api_version }}'

      # == Redirect Farm for Latest Stable
      # /stable -> /api_version

      - name: Build redirect farm
        run: nix build .#manual.redirectFarm -L
        if: ${{ env.api_version == env.latest_stable_api }}

      - name: Deploy redirect farm
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: result-redirectFarm
          target-folder: stable
        if: ${{ env.api_version == env.latest_stable_api }}
